FROM docker:cli
# install required tools
RUN apk add --no-cache bash curl unzip groff less jq
# install aws cli v2 (choose the correct architecture x86/arm)
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf aws awscliv2.zip

ENTRYPOINT ["bash"]